myproject/core/urls.py
from django.urls import path
from myproject.core import views as v


app_name = 'core'


urlpatterns = [
    path('', v.index, name='index'),
    path('api/products/', v.api_product, name='api_product'),
    path('api/shopping-items/add/', v.api_shopping_items_add, name='api_shopping_items_add'),
]

myproject/shopping/urls.py
from django.urls import path
from myproject.shopping import views as v


app_name = 'shopping'


urlpatterns = [
    path('shopping/', v.shopping, name='shopping'),
    path('cart-items/<int:pk>/', v.cart_items, name='cart_items'),
]

myproject/urls.py
from django.urls import include, path
from django.contrib import admin


urlpatterns = [
    path('', include('myproject.core.urls', namespace='core')),
    path('shopping/', include('myproject.shopping.urls', namespace='shopping')),
    path('admin/', admin.site.urls),
]

myproject/shopping/models.py
from django.db import models


class Shop(models.Model):
    customer = models.CharField('cliente', max_length=100)
    created = models.DateTimeField('criado em', auto_now_add=True, auto_now=False)

    class Meta:
        ordering = ('-pk',)
        verbose_name = 'compra'
        verbose_name_plural = 'compras'

    def __str__(self):
        return self.customer


class Product(models.Model):
    name = models.CharField('nome', max_length=100, unique=True)
    price = models.DecimalField('preço', max_digits=6, decimal_places=2)

    class Meta:
        ordering = ('name',)
        verbose_name = 'produto'
        verbose_name_plural = 'produtos'

    def __str__(self):
        return self.name

    def to_dict(self):
        return {
            'value': self.pk,
            'text': self.name,
            'price': self.price
        }


class Cart(models.Model):
    shop = models.ForeignKey(
        Shop,
        related_name='compras',
        on_delete=models.CASCADE
    )
    product = models.ForeignKey(
        Product,
        related_name='products',
        on_delete=models.SET_NULL,
        null=True,
        blank=True
    )
    quantity = models.PositiveIntegerField('quantidade')
    price = models.DecimalField('preço', max_digits=6, decimal_places=2)

    class Meta:
        ordering = ('-pk',)
        verbose_name = 'carrinho'
        verbose_name_plural = 'carrinhos'

    def __str__(self):
        if self.shop:
            return f'{self.shop.pk}-{self.pk}-{self.product}'
        return str(self.pk)

    def get_subtotal(self):
        return self.price * (self.quantity or 0)

myproject/core/views.py
import json
from django.http import JsonResponse
from django.shortcuts import render
from django.views.decorators.csrf import csrf_exempt
from myproject.shopping.models import Product, Shop, Cart


def index(request):
    return render(request, 'index.html')


def api_product(request):
    products = Product.objects.all()
    data = [item.to_dict() for item in products]
    response = {'data': data}
    return JsonResponse(response)


@csrf_exempt
def api_shopping_items_add(request):
    request = request.POST
    customer = json.loads(request.get('customer'))
    products = json.loads(request.get('products'))

    shop = Shop.objects.create(customer=customer)

    for product in products:
        product_obj = Product.objects.get(pk=product['pk'])
        quantity = product['quantity']
        price = product['price']

        Cart.objects.create(
            shop=shop,
            product=product_obj,
            quantity=quantity,
            price=price
        )
    response = {'data': shop.pk}
    return JsonResponse(response)

myproject/shopping/views.py
from django.shortcuts import render
from .models import Cart


def shopping(request):
    template_name = 'shopping.html'
    return render(request, template_name)


def cart_items(request, pk):
    template_name = 'cart_items.html'
    carts = Cart.objects.filter(shop=pk)

    qs = carts.values_list('price', 'quantity') or 0
    total = sum(map(lambda q: q[0] * q[1], qs))

    context = {'object_list': carts, 'total': total}
    return render(request, template_name, context)

myproject/core/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="shortcut icon" href="https://www.djangoproject.com/favicon.ico">
  <title>Carrinho de compras</title>

  <!-- Bootstrap core CSS -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">

  <!-- Font-awesome -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">

  <!-- vue-toast-notification -->
  <link href="https://cdn.jsdelivr.net/npm/vue-toast-notification/dist/theme-sugar.css" rel="stylesheet">


  <link rel="stylesheet" href="{% static 'css/style.css' %}">

  <style>
    body {
      margin-top: 70px;
    }
  </style>

</head>
<body>

  {% include "includes/nav.html" %}

  <div class="container">
    {% block content %}{% endblock content %}
  </div>

  <!-- VueJS -->
  <script src="https://cdn.jsdelivr.net/npm/vue/dist/vue.js"></script>

  <!-- axios -->
  <script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>

  <!-- vue-toast-notification -->
  <script src="https://cdn.jsdelivr.net/npm/vue-toast-notification"></script>

  {% block js %}{% endblock js %}

</body>
</html>

myproject/core/templates/includes/nav.html
<!-- https://getbootstrap.com/docs/4.0/examples/starter-template/ -->
<!-- https://github.com/JTruax/bootstrap-starter-template/blob/master/template/start.html -->

<nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
    <a class="navbar-brand" href="{% url 'core:index' %}">Carrinho de compras</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarsExampleDefault">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'core:index' %}">Home <span class="sr-only">(current)</span></a>
            </li>
        </ul>
    </div>
</nav>

myproject/core/templates/index.html
{% extends "base.html" %}
{% load static %}

{% block content %}
  <div class="jumbotron text-center">
    <p>Este é um projeto feito com <a href="https://www.djangoproject.com/" target="_blank">Django</a> e <a href="https://vuejs.org/" target="_blank">VueJS</a>.</p>
    <p>
      <a href="https://github.com/rg3915/carrinho-de-compras-django-vuejs" target="_blank">Veja no GitHub</a>
    </p>
    <a class="btn btn-primary" href="{% url 'shopping:shopping' %}">Fazer uma compra</a>
  </div>
{% endblock content %}

myproject/shopping/templates/cart_items.html
{% extends "base.html" %}
{% load static %}

{% block content %}

<div id="app" class="text-center">
  <div class="row">
    <div class="col-10">
      <div class="mt-4">
        <h3 class="text-left">Confirmação de compra</h3>
        <table class="table table-hover">
          <thead>
            <tr>
              <th class="text-left">Produto</th>
              <th>Quantidade</th>
              <th>Preço</th>
              <th>Subtotal</th>
            </tr>
          </thead>
          <tbody>
            {% for object in object_list %}
              <tr>
                <td class="text-left">{{ object.product.name }}</td>
                <td>{{ object.quantity }}</td>
                <td>
                  <div class="d-flex">
                    <div>R$</div>
                    <div class="ml-auto">{{ object.price }}</div>
                  </div>
                </td>
                <td>
                  <div class="d-flex">
                    <div>R$</div>
                    <div class="ml-auto">{{ object.get_subtotal }}</div>
                  </div>
                </td>
              </tr>
            {% endfor %}
          </tbody>
          <tfoot>
            <tr>
              <th colspan="3" class="text-right">Total</th>
              <th>
                <div class="d-flex">
                  <div>R$</div>
                  <div class="ml-auto">{{ total }}</div>
                </div>
              </th>
            </tr>
          </tfoot>
        </table>
      </div>
    </div>
  </div>
</div>

{% endblock content %}

myproject/shopping/templates/shopping.html
{% extends "base.html" %}
{% load static %}

{% block content %}

<div id="app" class="text-center">
  <div class="row">
    <div class="col-10">
      <form action="." method="POST">
        <input id="customer" class="form-control" type="text" v-model="form.customer" placeholder="Cliente" />
      </form>

      <div class="mt-4">
        <table class="table table-hover table-borderless">
          <thead>
            <tr>
              <th>Produto</th>
              <th>Quantidade</th>
              <th>Preço</th>
              <th>Subtotal</th>
              <th></th>
            </tr>
          </thead>
          <tbody class="mytable">
            <tr>
              <td class="w40">
                <select id="productName" class="form-control" v-model="currentProduct.pk" @change="onProductChange()">
                  <option selected value="">---</option>
                  <option v-for="product in products" :key="product.value" :value="product.value">${ product.text }</option>
                </select>
              </td>
              <td>
                <input id="productQuantity" class="form-control text-center" type="number" min="0" v-model="currentProduct.quantity" />
              </td>
              <td>
                <div class="input-group mm-2">
                  <div class="input-group-prepend">
                    <span class="input-group-text" id="basic-addon1">R$</span>
                  </div>
                  <input id="productPrice" class="form-control" type="number" min="0" step="0.01" v-model="currentProduct.price">
                </div>
              </td>
              <td class="w15">
                <div class="d-flex input-group mm-2">
                  <div>R$</div>
                  <div class="ml-auto">${ (currentProduct.price * currentProduct.quantity) | formatPrice }</div>
                </div>
              </td>
              <td>
                <button id="btnSubmit" class="btn btn-success" @click="addProduct">
                  <i class="fa fa-plus"></i>
                </button>
              </td>
            </tr>
          </tbody>
        </table>

        <hr>

        <table id="myTable" class="table table-hover table-borderless">
          <tbody>
            <tr v-for="(cart, i) in cartItems" :key="i">
              <td class="w40">
                <select :id="'name'+i" class="form-control" v-model="cart.pk" @change="onProductChange(cart, $event)">
                  <option selected value="">---</option>
                  <option v-for="product in products" :key="product.value" :value="product.value">${ product.text }</option>
                </select>
              </td>
              <td>
                <input :id="'quantity'+i" class="form-control text-center" type="number" min="0" v-model="cart.quantity" />
              </td>
              <td>
                <div class="input-group mm-2">
                  <div class="input-group-prepend">
                    <span class="input-group-text" id="basic-addon1">R$</span>
                  </div>
                  <input :id="'price'+i" class="form-control" type="number" min="0" step="0.01" v-model="cart.price" />
                </div>
              </td>
              <td class="w15">
                <div class="d-flex input-group mm-2">
                  <div>R$</div>
                  <div class="ml-auto">${ (cart.price * cart.quantity) | formatPrice }</div>
                </div>
              </td>
              <td>
                <button class="btn btn-link">
                  <i class="fa fa-close close" @click="deleteProduct(cart)"></i>
                </button>
              </td>
            </tr>
          </tbody>
          <tfoot class="lead">
            <tr>
              <th colspan="3" class="text-right">Total</th>
              <th class="text-left">R$ <span class="pull-right">${ cartValue | formatPrice }</span></th>
              <th></th>
            </tr>
            <tr>
              <th class="text-left">
                <button id="btnAddLine" class="btn btn-success" @click="addLine">
                  <i class="fa fa-plus"></i> Adicionar
                </button>
              </th>
              <th colspan="2" class="text-right">
                <button id="btnSave" class="btn btn-primary" @click="submitForm">
                  <i class="fa fa-floppy-o"></i> Salvar
                </button>
              </th>
              <th class="text-right">
                <button id="btnCancel" class="btn btn-danger" @click="resetForm">
                  <i class="fa fa-close"></i> Cancelar
                </button>
              </th>
            </tr>
          </tfoot>
        </table>
      </div>

    </div>
  </div>
</div>

{% endblock content %}

{% block js %}
  <script src="{% static 'js/app.js' %}"></script>
{% endblock js %}